### ISSUE TITLE
rename the cli to "pocket-curses"

### ISSUE THREAD

**Issue by m040601** [xoolive/pocket_curses#1]
Hi thanks for your work in this project. Very nice example of using curses.
Would you consider renaming the executable to something more unique ?
Something with "curses" in  the name ?

I test many pocket cli apps on my system and sometimes find it confusing and loose track of which app, executable, token credentials config file etc belongs to whom.
There are many many pocket scripts on github (go , python, node ). Many forget this, and the result is many have the same simple "pocket" name.
There is for example an older go cli app that also instals a cli simply called "pocket", https://github.com/junkblocker/go-pocket

Besides that you do ,
`pip install pocket-curses`

so it would be nice to get an executable with that name.

Additionally by renaming your cli app to something more unique, it would make it easy to create a package for distributing in a Linux distribution. But if the name conflicts with other apps similiarly named "pocket"  than it's a mess with the renaming.
I'd like to package your app to create an AUR Archlinux package.

Thanks in advance

PS There is already another one , https://aur.archlinux.org/packages/python-pocket/ , 
that will produce a cli named "pocket-cli"

**Comment by xoolive** [comment]
Hello @m040601 

If you want to change the executable name, you may edit this line https://github.com/xoolive/pocket_curses/blob/63581c60473f93063bd3c1a4a520af2387147ef1/setup.py#L21

I wrote this tool for my personal use and chose a name that is convenient to me. I see only one star to this repository and you are the one who put it so we are only two users 🤣 

Please free to fork the project and rename the tool in your version if you want; the license permits that. I don't think the project will evolve much more in the future. I have ideas of improvements but no time to work on them.
